shared: Add preview
wikimedia-gadgets/twinkle pull request #1275
Opened 2021-01-12 22:29 UTC by TheTVExpert

Closes #1264

2021-01-13 12:38 UTC, Amorymeltzer requested changes
@TheTVExpert I actually think this should use the pop-up style preview, rather than the in-line preview, since these are all huge templates.  It shouldn't be too complicated, there's a good example in the welcome module.

2021-01-13 14:06 UTC, TheTVExpert commented
@Amorymeltzer Done.

2021-01-17 19:34 UTC, Amorymeltzer requested changes
Just a couple minor suggestions about window size/style, but otherwise LGTM!  Appreciate the speedy call-to-action! 👍

2021-01-18 22:21 UTC, TheTVExpert commented
@Amorymeltzer Done.

2021-01-22 17:57 UTC, Amorymeltzer commented on modules/friendlyshared.js
> +	if (input.template !== undefined) {
Whoops, `input.template`, my bad!

2021-01-22 18:02 UTC, Amorymeltzer commented
LGTM!  Merged as 7a8e2a9

2021-01-22 18:02 UTC, closed without merging