speedy: fix bugs involving watchlist preferences
wikimedia-gadgets/twinkle pull request #1460
Opened 2021-11-17 08:29 UTC by NovemLinguae

Fixes #1427 All CSD tagged articles getting added to watchlist, despite selecting "don't add to watchlist"

Also fixes a bug where all CSD watchlisting was permanent, instead of taking into account the duration set in the user's preferences.

2021-11-17 13:49 UTC, siddharthvp requested changes
`let` is ES6, so can't be used here. Please use `var` instead and make sure that `npm run lint:fix` is passing.

2021-11-17 13:54 UTC, siddharthvp commented on modules/twinklespeedy.js
> +	// analyse each criterion to determine whether to watch the page/notify the creator
```suggestion
```
this comment has been duplicated

2021-12-20 07:42 UTC, NovemLinguae commented
This one is ready for re-review :)

2021-12-22 17:27 UTC, siddharthvp commented on modules/twinklespeedy.js
> +
I think this is equivalent to just 
```js
	var watchPage = normalizeds.some(function(csdCriteria) {
		return Twinkle.getPref('watchSpeedyPages').indexOf(csdCriteria) !== -1;
	}) && Twinkle.getPref('watchSpeedyExpiry');
```
?
Twinkle.getPref('watchSpeedyExpiry') doesn't need to be checked every time in the loop, and if normalizeds.some returns true, watchSpeedyExpiry being `'no'` gives the desired effect

2021-12-22 17:31 UTC, siddharthvp commented
From the issue, I can't reproduce the "unchecking all the boxes still [adds pages to watchlist]" bug. Also don't how this patch would fix that issue assuming it's there.

2022-06-14 10:30 UTC, merged