Store module prefills under Twinkle.prefill
wikimedia-gadgets/twinkle pull request #1683
Opened 2022-12-21 20:04 UTC by nardog

First stab at #1682. Gets relevant properties from the URL query on initialization and stores them under `Twinkle.prefill`, replacing mw.util.getParamValue(), so that the prefills may be configured after page load.

2022-12-22 03:31 UTC, NovemLinguae commented
No need to squash PRs on your end. We will squash when we accept the PR. There's a button that says "squash" that makes it easy.

Linter is currently failing. The message is below. If you don't mind, please fix when you get a chance.

```
787:1  error  Expected indentation of 3 tabs but found 2  indent

1 problem (1 error, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.

2022-12-22 03:40 UTC, nardog commented
Thanks, I saw the error but somehow I convinced myself it was a false positive. Fixed.

2023-03-08 05:52 UTC, NovemLinguae commented
Is this purely a refactor that doesn't change any behavior?

Is your goal to eventually prefill some stuff when hitting the [rollback] [vandalism] buttons on a user contributions page?

<img width="124" alt="image" src="https://user-images.githubusercontent.com/79697282/223630333-f5b05c5c-32f8-42f8-8212-5926e529e002.png">

2023-03-08 06:00 UTC, nardog commented
> Is this purely a refactor that doesn't change any behavior?

No, the patch should be a complete solution for #1682.

> Right now hitting those buttons doesn't visit the user talk page at all. It redirects to the article.

It's effective only if you have "Don't reload the page when rolling back from contributions or recent changes" on. Then if you roll back on a contributions page and open ARV, Warn, or Wel *on the same page*, certain fields in the dialog should be prefilled based on the last performed rollback.

2023-03-15 19:40 UTC, NovemLinguae requested changes

2023-03-16 05:11 UTC, nardog commented on twinkle.js
> +// Prefills in ARV/Warn/Welcome set by fluff
Is this good? The primary use case of the prefills is when a user talk is opened after a rollback or from the "talk" link on the right side of a diff.

(I think we should eventually stop using the URL search string for prefills and switch to [postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) or something instead, which this patch makes easier.)

2023-07-21 04:48 UTC, NovemLinguae commented
Took me quite awhile to figure out what this code is doing. I finally stopped looking at diffs and figured out that Twinkle peppers in some [rollback] and [vandalism] tags into the user's contribs. Can start testing properly now.

![image](https://github.com/wikimedia-gadgets/twinkle/assets/79697282/d92589f2-ac72-4ca0-8742-9661c38ce55e)

2023-07-21 05:25 UTC, merged