warn: allow user to preview/change edit summary before warning
wikimedia-gadgets/twinkle pull request #1818
Opened 2023-07-12 02:37 UTC by m-etroo

Upon opening the warning dialog, the user has the option to modify the edit summary that will eventually be used.

Currently, the edit summary (including any edits by the user) will be replaced entirely when a new warning is selected or when the linked page is changed. Not sure if this needs to be changed down the line to try to preserve the user's edits.

Resolves #1803 

![image](https://github.com/wikimedia-gadgets/twinkle/assets/50273080/eaddf401-edd2-4095-afde-99ecabc34dde)

2023-08-10 11:00 UTC, NovemLinguae requested changes
A pretty complex first patch. Nice work.

Can we delete the `<legend>Warning information</legend>`? I don't think it makes much sense to have linked page outside of it, and edit summary, optional message, and preview inside of it.

I think we can also move "edit summary" to above "linked page". Visually I'd like linked page and optional message grouped, since those both get turned off sometimes. Would be weird to have edit summary in the middle of that.

2023-08-12 14:23 UTC, siddharthvp reviewed
I'd put the edit summary at the bottom of the form, since that seems the least important input here.

2023-08-12 14:23 UTC, siddharthvp commented on modules/twinklewarn.js
> +	var messageData = $(e.target.form.sub_group).find('option[value="' + $(e.target.form.sub_group).val() + '"]').data('messageData');
There has to be a less error-prone (what if the value contains special chars?) and more elegant way to do this. 

Maybe something like `$(e.target.form.sub_group).find('option:selected')` ?

2024-11-14 01:14 UTC, NovemLinguae commented
Hi @m-etroo. We have a couple comments above, and this needs a rebase due to merge conflict. If you have time, would be great if you could take a look. I'm trying to clear the PR queue this week :)

2024-11-17 06:18 UTC, siddharthvp commented
Is there value in this feature? Edit summary is not important for talk page messages. If there is something you want to customize, it's probably to better to do it in the message itself than in the summary.  

This adds clutter to the dialog for something which I think is unlikely at all.

2024-11-17 06:20 UTC, siddharthvp commented
I don't think anyone has actually requested this. #1803 cites a thread where someone who said "I don't use TW much" was just asking if it's possible.

2024-11-17 08:55 UTC, NovemLinguae commented
There were some objections to this in https://github.com/wikimedia-gadgets/twinkle/pull/1818#issuecomment-2480943626, so I am closing as wontfix for now. Anyone can reopen if additional people would like this feature.

2024-11-17 08:55 UTC, closed without merging