tag: add {{No significant coverage (sports)}} and {{No significant coverage}}
wikimedia-gadgets/twinkle pull request #1834
Opened 2023-07-25 13:56 UTC by earlt612

Resolves #1817  + adds another

2024-03-01 04:02 UTC, Eejit43 commented
The template names have typos, they should be "signifi**c**ant" instead of "signifi**g**ant".

Additionally, more consistent descriptions would be:

`does not cite any sources containing significant coverage`
and
`sports biography that does not cite any sources containing significant coverage`

2024-04-15 23:44 UTC, NovemLinguae requested changes

2024-04-15 23:44 UTC, NovemLinguae commented on modules/friendlytag.js
> +			{ tag: 'No significant coverage (sports)', 'sports biography that does not cite any sources containing significant coverage' },
missing `description:`

2024-04-15 23:50 UTC, earlt612 commented
@NovemLinguae: Requested changes have been completed

2024-04-15 23:52 UTC, NovemLinguae commented
Thanks. I am finishing up a burst of work on https://github.com/wikimedia-gadgets/afc-helper. When I am done with that I will try to do a burst of work on Twinkle and catch up on all the PRs.

2024-04-16 02:26 UTC, earlt612 commented
No problem. Take your time

2024-09-04 23:41 UTC, NovemLinguae commented
{{No significant coverage}} is fine and can go in.

{{No significant coverage (sports)}} - we should wait and see how the [TFD](Let's see how the TFD goes for this one: https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2024_September_4#Template:No_significant_coverage_(sports)) goes. even if the TFD passes, maybe we should decline to add that one. I might need to think about it.

2024-09-06 02:09 UTC, NovemLinguae approved these changes

2024-09-06 02:10 UTC, NovemLinguae commented
The TFD is leaning keep. This PR has sat long enough. Let's approve it and get it in :)

2024-09-06 02:10 UTC, merged